package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1



/**
 * Audiovisual generated by hbm2java
 */
public class Audiovisual  implements java.io.Serializable {


     private int idAudioVisual;
     private Elemento elemento;
     private TipoAudiovisual tipoAudiovisual;
     private String titulo;
     private String autor1;
     private String autor2;
     private String autor3;
     private String autor4;
     private String fechaPub;
     private String duracion;
     private double precio;
     private Integer estadoBorrado;

    public Audiovisual() {
    }

	
    public Audiovisual(int idAudioVisual, Elemento elemento, TipoAudiovisual tipoAudiovisual, String titulo, String autor1, String fechaPub, String duracion, double precio) {
        this.idAudioVisual = idAudioVisual;
        this.elemento = elemento;
        this.tipoAudiovisual = tipoAudiovisual;
        this.titulo = titulo;
        this.autor1 = autor1;
        this.fechaPub = fechaPub;
        this.duracion = duracion;
        this.precio = precio;
    }
    public Audiovisual(int idAudioVisual, Elemento elemento, TipoAudiovisual tipoAudiovisual, String titulo, String autor1, String autor2, String autor3, String autor4, String fechaPub, String duracion, double precio, Integer estadoBorrado) {
       this.idAudioVisual = idAudioVisual;
       this.elemento = elemento;
       this.tipoAudiovisual = tipoAudiovisual;
       this.titulo = titulo;
       this.autor1 = autor1;
       this.autor2 = autor2;
       this.autor3 = autor3;
       this.autor4 = autor4;
       this.fechaPub = fechaPub;
       this.duracion = duracion;
       this.precio = precio;
       this.estadoBorrado = estadoBorrado;
    }
   
    public int getIdAudioVisual() {
        return this.idAudioVisual;
    }
    
    public void setIdAudioVisual(int idAudioVisual) {
        this.idAudioVisual = idAudioVisual;
    }
    public Elemento getElemento() {
        return this.elemento;
    }
    
    public void setElemento(Elemento elemento) {
        this.elemento = elemento;
    }
    public TipoAudiovisual getTipoAudiovisual() {
        return this.tipoAudiovisual;
    }
    
    public void setTipoAudiovisual(TipoAudiovisual tipoAudiovisual) {
        this.tipoAudiovisual = tipoAudiovisual;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor1() {
        return this.autor1;
    }
    
    public void setAutor1(String autor1) {
        this.autor1 = autor1;
    }
    public String getAutor2() {
        return this.autor2;
    }
    
    public void setAutor2(String autor2) {
        this.autor2 = autor2;
    }
    public String getAutor3() {
        return this.autor3;
    }
    
    public void setAutor3(String autor3) {
        this.autor3 = autor3;
    }
    public String getAutor4() {
        return this.autor4;
    }
    
    public void setAutor4(String autor4) {
        this.autor4 = autor4;
    }
    public String getFechaPub() {
        return this.fechaPub;
    }
    
    public void setFechaPub(String fechaPub) {
        this.fechaPub = fechaPub;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }




}


