package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Colonia generated by hbm2java
 */
public class Colonia  implements java.io.Serializable {


     private int idColonia;
     private Cp cp;
     private Delegacion delegacion;
     private String nombreCol;
     private Set contactos = new HashSet(0);

    public Colonia() {
    }

	
    public Colonia(int idColonia, Cp cp, Delegacion delegacion, String nombreCol) {
        this.idColonia = idColonia;
        this.cp = cp;
        this.delegacion = delegacion;
        this.nombreCol = nombreCol;
    }
    public Colonia(int idColonia, Cp cp, Delegacion delegacion, String nombreCol, Set contactos) {
       this.idColonia = idColonia;
       this.cp = cp;
       this.delegacion = delegacion;
       this.nombreCol = nombreCol;
       this.contactos = contactos;
    }
   
    public int getIdColonia() {
        return this.idColonia;
    }
    
    public void setIdColonia(int idColonia) {
        this.idColonia = idColonia;
    }
    public Cp getCp() {
        return this.cp;
    }
    
    public void setCp(Cp cp) {
        this.cp = cp;
    }
    public Delegacion getDelegacion() {
        return this.delegacion;
    }
    
    public void setDelegacion(Delegacion delegacion) {
        this.delegacion = delegacion;
    }
    public String getNombreCol() {
        return this.nombreCol;
    }
    
    public void setNombreCol(String nombreCol) {
        this.nombreCol = nombreCol;
    }
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }




}


