package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cp generated by hbm2java
 */
public class Cp  implements java.io.Serializable {


     private int idCp;
     private String cp;
     private Set colonias = new HashSet(0);

    public Cp() {
    }

	
    public Cp(int idCp, String cp) {
        this.idCp = idCp;
        this.cp = cp;
    }
    public Cp(int idCp, String cp, Set colonias) {
       this.idCp = idCp;
       this.cp = cp;
       this.colonias = colonias;
    }
   
    public int getIdCp() {
        return this.idCp;
    }
    
    public void setIdCp(int idCp) {
        this.idCp = idCp;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Set getColonias() {
        return this.colonias;
    }
    
    public void setColonias(Set colonias) {
        this.colonias = colonias;
    }




}


