package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Credencial generated by hbm2java
 */
public class Credencial  implements java.io.Serializable {


     private int idCredencial;
     private Lector lector;
     private Date fechaEmision;

    public Credencial() {
    }

    public Credencial(int idCredencial, Lector lector, Date fechaEmision) {
       this.idCredencial = idCredencial;
       this.lector = lector;
       this.fechaEmision = fechaEmision;
    }
   
    public int getIdCredencial() {
        return this.idCredencial;
    }
    
    public void setIdCredencial(int idCredencial) {
        this.idCredencial = idCredencial;
    }
    public Lector getLector() {
        return this.lector;
    }
    
    public void setLector(Lector lector) {
        this.lector = lector;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }




}


