package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1



/**
 * Datosacademicos generated by hbm2java
 */
public class Datosacademicos  implements java.io.Serializable {


     private int idDatosAcademicos;
     private Estudiante estudiante;
     private int semestre;
     private String turno;

    public Datosacademicos() {
    }

    public Datosacademicos(int idDatosAcademicos, Estudiante estudiante, int semestre, String turno) {
       this.idDatosAcademicos = idDatosAcademicos;
       this.estudiante = estudiante;
       this.semestre = semestre;
       this.turno = turno;
    }
   
    public int getIdDatosAcademicos() {
        return this.idDatosAcademicos;
    }
    
    public void setIdDatosAcademicos(int idDatosAcademicos) {
        this.idDatosAcademicos = idDatosAcademicos;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public int getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(int semestre) {
        this.semestre = semestre;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }




}


