package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1



/**
 * Dmultaeje generated by hbm2java
 */
public class Dmultaeje  implements java.io.Serializable {


     private int idDmultaEje;
     private Ejemplar ejemplar;
     private Multa multa;
     private Tipomulta tipomulta;

    public Dmultaeje() {
    }

    public Dmultaeje(int idDmultaEje, Ejemplar ejemplar, Multa multa, Tipomulta tipomulta) {
       this.idDmultaEje = idDmultaEje;
       this.ejemplar = ejemplar;
       this.multa = multa;
       this.tipomulta = tipomulta;
    }
   
    public int getIdDmultaEje() {
        return this.idDmultaEje;
    }
    
    public void setIdDmultaEje(int idDmultaEje) {
        this.idDmultaEje = idDmultaEje;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Multa getMulta() {
        return this.multa;
    }
    
    public void setMulta(Multa multa) {
        this.multa = multa;
    }
    public Tipomulta getTipomulta() {
        return this.tipomulta;
    }
    
    public void setTipomulta(Tipomulta tipomulta) {
        this.tipomulta = tipomulta;
    }




}


