package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private String numEmpleado;
     private Lector lector;
     private String nombre;
     private String primerAp;
     private String segundoAp;
     private Date fechaNac;
     private String curp;

    public Docente() {
    }

    public Docente(String numEmpleado, Lector lector, String nombre, String primerAp, String segundoAp, Date fechaNac, String curp) {
       this.numEmpleado = numEmpleado;
       this.lector = lector;
       this.nombre = nombre;
       this.primerAp = primerAp;
       this.segundoAp = segundoAp;
       this.fechaNac = fechaNac;
       this.curp = curp;
    }
   
    public String getNumEmpleado() {
        return this.numEmpleado;
    }
    
    public void setNumEmpleado(String numEmpleado) {
        this.numEmpleado = numEmpleado;
    }
    public Lector getLector() {
        return this.lector;
    }
    
    public void setLector(Lector lector) {
        this.lector = lector;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerAp() {
        return this.primerAp;
    }
    
    public void setPrimerAp(String primerAp) {
        this.primerAp = primerAp;
    }
    public String getSegundoAp() {
        return this.segundoAp;
    }
    
    public void setSegundoAp(String segundoAp) {
        this.segundoAp = segundoAp;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }




}


