package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1



/**
 * DPresot generated by hbm2java
 */
public class DPresot  implements java.io.Serializable {


     private int idDPresOt;
     private Elemento elemento;
     private Prestamootros prestamootros;

    public DPresot() {
    }

    public DPresot(int idDPresOt, Elemento elemento, Prestamootros prestamootros) {
       this.idDPresOt = idDPresOt;
       this.elemento = elemento;
       this.prestamootros = prestamootros;
    }
   
    public int getIdDPresOt() {
        return this.idDPresOt;
    }
    
    public void setIdDPresOt(int idDPresOt) {
        this.idDPresOt = idDPresOt;
    }
    public Elemento getElemento() {
        return this.elemento;
    }
    
    public void setElemento(Elemento elemento) {
        this.elemento = elemento;
    }
    public Prestamootros getPrestamootros() {
        return this.prestamootros;
    }
    
    public void setPrestamootros(Prestamootros prestamootros) {
        this.prestamootros = prestamootros;
    }




}


