package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1



/**
 * DPrestamo generated by hbm2java
 */
public class DPrestamo  implements java.io.Serializable {


     private int idDPrestamo;
     private Ejemplar ejemplar;
     private Prestamo prestamo;

    public DPrestamo() {
    }

    public DPrestamo(int idDPrestamo, Ejemplar ejemplar, Prestamo prestamo) {
       this.idDPrestamo = idDPrestamo;
       this.ejemplar = ejemplar;
       this.prestamo = prestamo;
    }
   
    public int getIdDPrestamo() {
        return this.idDPrestamo;
    }
    
    public void setIdDPrestamo(int idDPrestamo) {
        this.idDPrestamo = idDPrestamo;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Prestamo getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }




}


