package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Elemento generated by hbm2java
 */
public class Elemento  implements java.io.Serializable {


     private int idElemento;
     private Estadoelemnto estadoelemnto;
     private Set audiovisuals = new HashSet(0);
     private Set computos = new HashSet(0);
     private Set DPresots = new HashSet(0);
     private Set tts = new HashSet(0);

    public Elemento() {
    }

	
    public Elemento(int idElemento, Estadoelemnto estadoelemnto) {
        this.idElemento = idElemento;
        this.estadoelemnto = estadoelemnto;
    }
    public Elemento(int idElemento, Estadoelemnto estadoelemnto, Set audiovisuals, Set computos, Set DPresots, Set tts) {
       this.idElemento = idElemento;
       this.estadoelemnto = estadoelemnto;
       this.audiovisuals = audiovisuals;
       this.computos = computos;
       this.DPresots = DPresots;
       this.tts = tts;
    }
   
    public int getIdElemento() {
        return this.idElemento;
    }
    
    public void setIdElemento(int idElemento) {
        this.idElemento = idElemento;
    }
    public Estadoelemnto getEstadoelemnto() {
        return this.estadoelemnto;
    }
    
    public void setEstadoelemnto(Estadoelemnto estadoelemnto) {
        this.estadoelemnto = estadoelemnto;
    }
    public Set getAudiovisuals() {
        return this.audiovisuals;
    }
    
    public void setAudiovisuals(Set audiovisuals) {
        this.audiovisuals = audiovisuals;
    }
    public Set getComputos() {
        return this.computos;
    }
    
    public void setComputos(Set computos) {
        this.computos = computos;
    }
    public Set getDPresots() {
        return this.DPresots;
    }
    
    public void setDPresots(Set DPresots) {
        this.DPresots = DPresots;
    }
    public Set getTts() {
        return this.tts;
    }
    
    public void setTts(Set tts) {
        this.tts = tts;
    }




}


