package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private Contacto contacto;
     private Estadoempleado estadoempleado;
     private Rolempleado rolempleado;
     private Usuario usuario;
     private String nombre;
     private String primerAp;
     private String segundoAp;
     private Date fechaAdmision;
     private Integer estadoBorrado;

    public Empleado() {
    }

	
    public Empleado(int idEmpleado, Contacto contacto, Estadoempleado estadoempleado, Rolempleado rolempleado, Usuario usuario, String nombre, String primerAp, String segundoAp, Date fechaAdmision) {
        this.idEmpleado = idEmpleado;
        this.contacto = contacto;
        this.estadoempleado = estadoempleado;
        this.rolempleado = rolempleado;
        this.usuario = usuario;
        this.nombre = nombre;
        this.primerAp = primerAp;
        this.segundoAp = segundoAp;
        this.fechaAdmision = fechaAdmision;
    }
    public Empleado(int idEmpleado, Contacto contacto, Estadoempleado estadoempleado, Rolempleado rolempleado, Usuario usuario, String nombre, String primerAp, String segundoAp, Date fechaAdmision, Integer estadoBorrado) {
       this.idEmpleado = idEmpleado;
       this.contacto = contacto;
       this.estadoempleado = estadoempleado;
       this.rolempleado = rolempleado;
       this.usuario = usuario;
       this.nombre = nombre;
       this.primerAp = primerAp;
       this.segundoAp = segundoAp;
       this.fechaAdmision = fechaAdmision;
       this.estadoBorrado = estadoBorrado;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public Estadoempleado getEstadoempleado() {
        return this.estadoempleado;
    }
    
    public void setEstadoempleado(Estadoempleado estadoempleado) {
        this.estadoempleado = estadoempleado;
    }
    public Rolempleado getRolempleado() {
        return this.rolempleado;
    }
    
    public void setRolempleado(Rolempleado rolempleado) {
        this.rolempleado = rolempleado;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerAp() {
        return this.primerAp;
    }
    
    public void setPrimerAp(String primerAp) {
        this.primerAp = primerAp;
    }
    public String getSegundoAp() {
        return this.segundoAp;
    }
    
    public void setSegundoAp(String segundoAp) {
        this.segundoAp = segundoAp;
    }
    public Date getFechaAdmision() {
        return this.fechaAdmision;
    }
    
    public void setFechaAdmision(Date fechaAdmision) {
        this.fechaAdmision = fechaAdmision;
    }
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }




}


