package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private int idEscuela;
     private String nombreEsc;
     private Set prestamointers = new HashSet(0);
     private Set prestamoexternos = new HashSet(0);

    public Escuela() {
    }

	
    public Escuela(int idEscuela, String nombreEsc) {
        this.idEscuela = idEscuela;
        this.nombreEsc = nombreEsc;
    }
    public Escuela(int idEscuela, String nombreEsc, Set prestamointers, Set prestamoexternos) {
       this.idEscuela = idEscuela;
       this.nombreEsc = nombreEsc;
       this.prestamointers = prestamointers;
       this.prestamoexternos = prestamoexternos;
    }
   
    public int getIdEscuela() {
        return this.idEscuela;
    }
    
    public void setIdEscuela(int idEscuela) {
        this.idEscuela = idEscuela;
    }
    public String getNombreEsc() {
        return this.nombreEsc;
    }
    
    public void setNombreEsc(String nombreEsc) {
        this.nombreEsc = nombreEsc;
    }
    public Set getPrestamointers() {
        return this.prestamointers;
    }
    
    public void setPrestamointers(Set prestamointers) {
        this.prestamointers = prestamointers;
    }
    public Set getPrestamoexternos() {
        return this.prestamoexternos;
    }
    
    public void setPrestamoexternos(Set prestamoexternos) {
        this.prestamoexternos = prestamoexternos;
    }




}


