package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estadoempleado generated by hbm2java
 */
public class Estadoempleado  implements java.io.Serializable {


     private int idEdoEmp;
     private String edoEmp;
     private Set empleados = new HashSet(0);

    public Estadoempleado() {
    }

	
    public Estadoempleado(int idEdoEmp, String edoEmp) {
        this.idEdoEmp = idEdoEmp;
        this.edoEmp = edoEmp;
    }
    public Estadoempleado(int idEdoEmp, String edoEmp, Set empleados) {
       this.idEdoEmp = idEdoEmp;
       this.edoEmp = edoEmp;
       this.empleados = empleados;
    }
   
    public int getIdEdoEmp() {
        return this.idEdoEmp;
    }
    
    public void setIdEdoEmp(int idEdoEmp) {
        this.idEdoEmp = idEdoEmp;
    }
    public String getEdoEmp() {
        return this.edoEmp;
    }
    
    public void setEdoEmp(String edoEmp) {
        this.edoEmp = edoEmp;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


