package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String boleta;
     private Estadoestudiante estadoestudiante;
     private Lector lector;
     private Tipoestudiante tipoestudiante;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private String curp;
     private String fechaNac;
     private Set datosacademicoses = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(String boleta, Estadoestudiante estadoestudiante, Lector lector, Tipoestudiante tipoestudiante, String nombre, String primerApellido, String segundoApellido, String curp, String fechaNac) {
        this.boleta = boleta;
        this.estadoestudiante = estadoestudiante;
        this.lector = lector;
        this.tipoestudiante = tipoestudiante;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.curp = curp;
        this.fechaNac = fechaNac;
    }
    public Estudiante(String boleta, Estadoestudiante estadoestudiante, Lector lector, Tipoestudiante tipoestudiante, String nombre, String primerApellido, String segundoApellido, String curp, String fechaNac, Set datosacademicoses) {
       this.boleta = boleta;
       this.estadoestudiante = estadoestudiante;
       this.lector = lector;
       this.tipoestudiante = tipoestudiante;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.curp = curp;
       this.fechaNac = fechaNac;
       this.datosacademicoses = datosacademicoses;
    }
   
    public String getBoleta() {
        return this.boleta;
    }
    
    public void setBoleta(String boleta) {
        this.boleta = boleta;
    }
    public Estadoestudiante getEstadoestudiante() {
        return this.estadoestudiante;
    }
    
    public void setEstadoestudiante(Estadoestudiante estadoestudiante) {
        this.estadoestudiante = estadoestudiante;
    }
    public Lector getLector() {
        return this.lector;
    }
    
    public void setLector(Lector lector) {
        this.lector = lector;
    }
    public Tipoestudiante getTipoestudiante() {
        return this.tipoestudiante;
    }
    
    public void setTipoestudiante(Tipoestudiante tipoestudiante) {
        this.tipoestudiante = tipoestudiante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(String fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Set getDatosacademicoses() {
        return this.datosacademicoses;
    }
    
    public void setDatosacademicoses(Set datosacademicoses) {
        this.datosacademicoses = datosacademicoses;
    }




}


