package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lector generated by hbm2java
 */
public class Lector  implements java.io.Serializable {


     private int idLector;
     private Contacto contacto;
     private Usuario usuario;
     private Integer estadoBorrado;
     private Set docentes = new HashSet(0);
     private Set credencials = new HashSet(0);
     private Set estudiantes = new HashSet(0);
     private Set prestamointers = new HashSet(0);
     private Set prestamootroses = new HashSet(0);
     private Set prestamos = new HashSet(0);

    public Lector() {
    }

	
    public Lector(int idLector, Contacto contacto, Usuario usuario) {
        this.idLector = idLector;
        this.contacto = contacto;
        this.usuario = usuario;
    }
    public Lector(int idLector, Contacto contacto, Usuario usuario, Integer estadoBorrado, Set docentes, Set credencials, Set estudiantes, Set prestamointers, Set prestamootroses, Set prestamos) {
       this.idLector = idLector;
       this.contacto = contacto;
       this.usuario = usuario;
       this.estadoBorrado = estadoBorrado;
       this.docentes = docentes;
       this.credencials = credencials;
       this.estudiantes = estudiantes;
       this.prestamointers = prestamointers;
       this.prestamootroses = prestamootroses;
       this.prestamos = prestamos;
    }
   
    public int getIdLector() {
        return this.idLector;
    }
    
    public void setIdLector(int idLector) {
        this.idLector = idLector;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getCredencials() {
        return this.credencials;
    }
    
    public void setCredencials(Set credencials) {
        this.credencials = credencials;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Set getPrestamointers() {
        return this.prestamointers;
    }
    
    public void setPrestamointers(Set prestamointers) {
        this.prestamointers = prestamointers;
    }
    public Set getPrestamootroses() {
        return this.prestamootroses;
    }
    
    public void setPrestamootroses(Set prestamootroses) {
        this.prestamootroses = prestamootroses;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


