package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private String isbnId;
     private String titulo;
     private String autor1;
     private String autor2;
     private String autor3;
     private String autor4;
     private String editorial;
     private String fechaPub;
     private int noPags;
     private int edicion;
     private double precio;
     private Integer estadoBorrado;
     private Set ejemplars = new HashSet(0);
     private Set tipoAudiovisuals = new HashSet(0);

    public Libro() {
    }

	
    public Libro(String isbnId, String titulo, String autor1, String editorial, String fechaPub, int noPags, int edicion, double precio) {
        this.isbnId = isbnId;
        this.titulo = titulo;
        this.autor1 = autor1;
        this.editorial = editorial;
        this.fechaPub = fechaPub;
        this.noPags = noPags;
        this.edicion = edicion;
        this.precio = precio;
    }
    public Libro(String isbnId, String titulo, String autor1, String autor2, String autor3, String autor4, String editorial, String fechaPub, int noPags, int edicion, double precio, Integer estadoBorrado, Set ejemplars, Set tipoAudiovisuals) {
       this.isbnId = isbnId;
       this.titulo = titulo;
       this.autor1 = autor1;
       this.autor2 = autor2;
       this.autor3 = autor3;
       this.autor4 = autor4;
       this.editorial = editorial;
       this.fechaPub = fechaPub;
       this.noPags = noPags;
       this.edicion = edicion;
       this.precio = precio;
       this.estadoBorrado = estadoBorrado;
       this.ejemplars = ejemplars;
       this.tipoAudiovisuals = tipoAudiovisuals;
    }
   
    public String getIsbnId() {
        return this.isbnId;
    }
    
    public void setIsbnId(String isbnId) {
        this.isbnId = isbnId;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor1() {
        return this.autor1;
    }
    
    public void setAutor1(String autor1) {
        this.autor1 = autor1;
    }
    public String getAutor2() {
        return this.autor2;
    }
    
    public void setAutor2(String autor2) {
        this.autor2 = autor2;
    }
    public String getAutor3() {
        return this.autor3;
    }
    
    public void setAutor3(String autor3) {
        this.autor3 = autor3;
    }
    public String getAutor4() {
        return this.autor4;
    }
    
    public void setAutor4(String autor4) {
        this.autor4 = autor4;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getFechaPub() {
        return this.fechaPub;
    }
    
    public void setFechaPub(String fechaPub) {
        this.fechaPub = fechaPub;
    }
    public int getNoPags() {
        return this.noPags;
    }
    
    public void setNoPags(int noPags) {
        this.noPags = noPags;
    }
    public int getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(int edicion) {
        this.edicion = edicion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }
    public Set getEjemplars() {
        return this.ejemplars;
    }
    
    public void setEjemplars(Set ejemplars) {
        this.ejemplars = ejemplars;
    }
    public Set getTipoAudiovisuals() {
        return this.tipoAudiovisuals;
    }
    
    public void setTipoAudiovisuals(Set tipoAudiovisuals) {
        this.tipoAudiovisuals = tipoAudiovisuals;
    }




}


