package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Multaextarna generated by hbm2java
 */
public class Multaextarna  implements java.io.Serializable {


     private Integer idMultaExtarna;
     private Prestamoexterno prestamoexterno;
     private double monto;
     private Date fechaInicio;
     private Date fechaPago;
     private int estado;

    public Multaextarna() {
    }

    public Multaextarna(Prestamoexterno prestamoexterno, double monto, Date fechaInicio, Date fechaPago, int estado) {
       this.prestamoexterno = prestamoexterno;
       this.monto = monto;
       this.fechaInicio = fechaInicio;
       this.fechaPago = fechaPago;
       this.estado = estado;
    }
   
    public Integer getIdMultaExtarna() {
        return this.idMultaExtarna;
    }
    
    public void setIdMultaExtarna(Integer idMultaExtarna) {
        this.idMultaExtarna = idMultaExtarna;
    }
    public Prestamoexterno getPrestamoexterno() {
        return this.prestamoexterno;
    }
    
    public void setPrestamoexterno(Prestamoexterno prestamoexterno) {
        this.prestamoexterno = prestamoexterno;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


