package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Multa generated by hbm2java
 */
public class Multa  implements java.io.Serializable {


     private int idMulta;
     private double monto;
     private Date fechaInicio;
     private Date fechaPago;
     private int estado;
     private Set dmultaejes = new HashSet(0);

    public Multa() {
    }

	
    public Multa(int idMulta, double monto, Date fechaInicio, Date fechaPago, int estado) {
        this.idMulta = idMulta;
        this.monto = monto;
        this.fechaInicio = fechaInicio;
        this.fechaPago = fechaPago;
        this.estado = estado;
    }
    public Multa(int idMulta, double monto, Date fechaInicio, Date fechaPago, int estado, Set dmultaejes) {
       this.idMulta = idMulta;
       this.monto = monto;
       this.fechaInicio = fechaInicio;
       this.fechaPago = fechaPago;
       this.estado = estado;
       this.dmultaejes = dmultaejes;
    }
   
    public int getIdMulta() {
        return this.idMulta;
    }
    
    public void setIdMulta(int idMulta) {
        this.idMulta = idMulta;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getDmultaejes() {
        return this.dmultaejes;
    }
    
    public void setDmultaejes(Set dmultaejes) {
        this.dmultaejes = dmultaejes;
    }




}


