package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prestamoexterno generated by hbm2java
 */
public class Prestamoexterno  implements java.io.Serializable {


     private int idPrestamoExterno;
     private Ejemplar ejemplar;
     private Escuela escuela;
     private String nombreP;
     private String primerApP;
     private String segundoApP;
     private String matricula;
     private Set multaextarnas = new HashSet(0);

    public Prestamoexterno() {
    }

	
    public Prestamoexterno(int idPrestamoExterno, Ejemplar ejemplar, Escuela escuela, String nombreP, String primerApP, String segundoApP, String matricula) {
        this.idPrestamoExterno = idPrestamoExterno;
        this.ejemplar = ejemplar;
        this.escuela = escuela;
        this.nombreP = nombreP;
        this.primerApP = primerApP;
        this.segundoApP = segundoApP;
        this.matricula = matricula;
    }
    public Prestamoexterno(int idPrestamoExterno, Ejemplar ejemplar, Escuela escuela, String nombreP, String primerApP, String segundoApP, String matricula, Set multaextarnas) {
       this.idPrestamoExterno = idPrestamoExterno;
       this.ejemplar = ejemplar;
       this.escuela = escuela;
       this.nombreP = nombreP;
       this.primerApP = primerApP;
       this.segundoApP = segundoApP;
       this.matricula = matricula;
       this.multaextarnas = multaextarnas;
    }
   
    public int getIdPrestamoExterno() {
        return this.idPrestamoExterno;
    }
    
    public void setIdPrestamoExterno(int idPrestamoExterno) {
        this.idPrestamoExterno = idPrestamoExterno;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getNombreP() {
        return this.nombreP;
    }
    
    public void setNombreP(String nombreP) {
        this.nombreP = nombreP;
    }
    public String getPrimerApP() {
        return this.primerApP;
    }
    
    public void setPrimerApP(String primerApP) {
        this.primerApP = primerApP;
    }
    public String getSegundoApP() {
        return this.segundoApP;
    }
    
    public void setSegundoApP(String segundoApP) {
        this.segundoApP = segundoApP;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Set getMultaextarnas() {
        return this.multaextarnas;
    }
    
    public void setMultaextarnas(Set multaextarnas) {
        this.multaextarnas = multaextarnas;
    }




}


