package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Prestamootros generated by hbm2java
 */
public class Prestamootros  implements java.io.Serializable {


     private int idPrestamoOtros;
     private Lector lector;
     private Date fechaInicio;
     private Date fechFin;
     private Integer edoPr;
     private Date horaInicio;
     private Date horaFin;
     private Set DPresots = new HashSet(0);

    public Prestamootros() {
    }

	
    public Prestamootros(int idPrestamoOtros, Lector lector, Date fechaInicio) {
        this.idPrestamoOtros = idPrestamoOtros;
        this.lector = lector;
        this.fechaInicio = fechaInicio;
    }
    public Prestamootros(int idPrestamoOtros, Lector lector, Date fechaInicio, Date fechFin, Integer edoPr, Date horaInicio, Date horaFin, Set DPresots) {
       this.idPrestamoOtros = idPrestamoOtros;
       this.lector = lector;
       this.fechaInicio = fechaInicio;
       this.fechFin = fechFin;
       this.edoPr = edoPr;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.DPresots = DPresots;
    }
   
    public int getIdPrestamoOtros() {
        return this.idPrestamoOtros;
    }
    
    public void setIdPrestamoOtros(int idPrestamoOtros) {
        this.idPrestamoOtros = idPrestamoOtros;
    }
    public Lector getLector() {
        return this.lector;
    }
    
    public void setLector(Lector lector) {
        this.lector = lector;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechFin() {
        return this.fechFin;
    }
    
    public void setFechFin(Date fechFin) {
        this.fechFin = fechFin;
    }
    public Integer getEdoPr() {
        return this.edoPr;
    }
    
    public void setEdoPr(Integer edoPr) {
        this.edoPr = edoPr;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Set getDPresots() {
        return this.DPresots;
    }
    
    public void setDPresots(Set DPresots) {
        this.DPresots = DPresots;
    }




}


