package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamointer generated by hbm2java
 */
public class Prestamointer  implements java.io.Serializable {


     private int idPrestamoInter;
     private Escuela escuela;
     private Lector lector;
     private String titulo;
     private String autor;
     private String edicion;
     private int publicacion;
     private String editorial;
     private Date fechaPrestamo;

    public Prestamointer() {
    }

    public Prestamointer(int idPrestamoInter, Escuela escuela, Lector lector, String titulo, String autor, String edicion, int publicacion, String editorial, Date fechaPrestamo) {
       this.idPrestamoInter = idPrestamoInter;
       this.escuela = escuela;
       this.lector = lector;
       this.titulo = titulo;
       this.autor = autor;
       this.edicion = edicion;
       this.publicacion = publicacion;
       this.editorial = editorial;
       this.fechaPrestamo = fechaPrestamo;
    }
   
    public int getIdPrestamoInter() {
        return this.idPrestamoInter;
    }
    
    public void setIdPrestamoInter(int idPrestamoInter) {
        this.idPrestamoInter = idPrestamoInter;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public Lector getLector() {
        return this.lector;
    }
    
    public void setLector(Lector lector) {
        this.lector = lector;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(String edicion) {
        this.edicion = edicion;
    }
    public int getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(int publicacion) {
        this.publicacion = publicacion;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }




}


