package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoestudiante generated by hbm2java
 */
public class Tipoestudiante  implements java.io.Serializable {


     private int idTipoEs;
     private String tipoEst;
     private Set estudiantes = new HashSet(0);

    public Tipoestudiante() {
    }

	
    public Tipoestudiante(int idTipoEs, String tipoEst) {
        this.idTipoEs = idTipoEs;
        this.tipoEst = tipoEst;
    }
    public Tipoestudiante(int idTipoEs, String tipoEst, Set estudiantes) {
       this.idTipoEs = idTipoEs;
       this.tipoEst = tipoEst;
       this.estudiantes = estudiantes;
    }
   
    public int getIdTipoEs() {
        return this.idTipoEs;
    }
    
    public void setIdTipoEs(int idTipoEs) {
        this.idTipoEs = idTipoEs;
    }
    public String getTipoEst() {
        return this.tipoEst;
    }
    
    public void setTipoEst(String tipoEst) {
        this.tipoEst = tipoEst;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


