package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAudiovisual generated by hbm2java
 */
public class TipoAudiovisual  implements java.io.Serializable {


     private int idTipoAudiovisual;
     private Libro libro;
     private String nombre;
     private Set audiovisuals = new HashSet(0);

    public TipoAudiovisual() {
    }

	
    public TipoAudiovisual(int idTipoAudiovisual, String nombre) {
        this.idTipoAudiovisual = idTipoAudiovisual;
        this.nombre = nombre;
    }
    public TipoAudiovisual(int idTipoAudiovisual, Libro libro, String nombre, Set audiovisuals) {
       this.idTipoAudiovisual = idTipoAudiovisual;
       this.libro = libro;
       this.nombre = nombre;
       this.audiovisuals = audiovisuals;
    }
   
    public int getIdTipoAudiovisual() {
        return this.idTipoAudiovisual;
    }
    
    public void setIdTipoAudiovisual(int idTipoAudiovisual) {
        this.idTipoAudiovisual = idTipoAudiovisual;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAudiovisuals() {
        return this.audiovisuals;
    }
    
    public void setAudiovisuals(Set audiovisuals) {
        this.audiovisuals = audiovisuals;
    }




}


