package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tt generated by hbm2java
 */
public class Tt  implements java.io.Serializable {


     private String noTt;
     private Elemento elemento;
     private String titulo;
     private Date fechaPresent;
     private String autor1;
     private String autor2;
     private String autor3;
     private String autor4;
     private String autor5;
     private String director1;
     private String director2;
     private Integer estadoBorrado;

    public Tt() {
    }

	
    public Tt(String noTt, Elemento elemento, String titulo, Date fechaPresent, String autor1, String director1) {
        this.noTt = noTt;
        this.elemento = elemento;
        this.titulo = titulo;
        this.fechaPresent = fechaPresent;
        this.autor1 = autor1;
        this.director1 = director1;
    }
    public Tt(String noTt, Elemento elemento, String titulo, Date fechaPresent, String autor1, String autor2, String autor3, String autor4, String autor5, String director1, String director2, Integer estadoBorrado) {
       this.noTt = noTt;
       this.elemento = elemento;
       this.titulo = titulo;
       this.fechaPresent = fechaPresent;
       this.autor1 = autor1;
       this.autor2 = autor2;
       this.autor3 = autor3;
       this.autor4 = autor4;
       this.autor5 = autor5;
       this.director1 = director1;
       this.director2 = director2;
       this.estadoBorrado = estadoBorrado;
    }
   
    public String getNoTt() {
        return this.noTt;
    }
    
    public void setNoTt(String noTt) {
        this.noTt = noTt;
    }
    public Elemento getElemento() {
        return this.elemento;
    }
    
    public void setElemento(Elemento elemento) {
        this.elemento = elemento;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFechaPresent() {
        return this.fechaPresent;
    }
    
    public void setFechaPresent(Date fechaPresent) {
        this.fechaPresent = fechaPresent;
    }
    public String getAutor1() {
        return this.autor1;
    }
    
    public void setAutor1(String autor1) {
        this.autor1 = autor1;
    }
    public String getAutor2() {
        return this.autor2;
    }
    
    public void setAutor2(String autor2) {
        this.autor2 = autor2;
    }
    public String getAutor3() {
        return this.autor3;
    }
    
    public void setAutor3(String autor3) {
        this.autor3 = autor3;
    }
    public String getAutor4() {
        return this.autor4;
    }
    
    public void setAutor4(String autor4) {
        this.autor4 = autor4;
    }
    public String getAutor5() {
        return this.autor5;
    }
    
    public void setAutor5(String autor5) {
        this.autor5 = autor5;
    }
    public String getDirector1() {
        return this.director1;
    }
    
    public void setDirector1(String director1) {
        this.director1 = director1;
    }
    public String getDirector2() {
        return this.director2;
    }
    
    public void setDirector2(String director2) {
        this.director2 = director2;
    }
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }




}


