package com.ipn.mx.escom.biblioteca.Pojos;
// Generated 24/05/2017 04:48:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int matricula;
     private String password;
     private int tipo;
     private Set empleados = new HashSet(0);
     private Set lectors = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int matricula, String password, int tipo) {
        this.matricula = matricula;
        this.password = password;
        this.tipo = tipo;
    }
    public Usuario(int matricula, String password, int tipo, Set empleados, Set lectors) {
       this.matricula = matricula;
       this.password = password;
       this.tipo = tipo;
       this.empleados = empleados;
       this.lectors = lectors;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getLectors() {
        return this.lectors;
    }
    
    public void setLectors(Set lectors) {
        this.lectors = lectors;
    }




}


